---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data("rest_inspec")

rest_inspec = rest_inspec |>
  filter(grade == "P") |>
  drop_na(violation_description)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Number of Grade P Restaurants by Borough

```{r}
boro_counts <- rest_inspec %>%
  group_by(boro) %>%
  summarize(count = n()) %>%
  arrange(desc(count))

boro_counts %>%
  plot_ly(x = ~boro, y = ~count, type = 'bar')
```

Column {data-width=650}
-----------------------------------------------------------------------

### Monthly Violation Count Over Time

```{r}
violation_data <- rest_inspec %>%
  mutate(month = floor_date(inspection_date, "month")) %>%
  group_by(month) %>%
  summarize(violation_count = n())

violation_data %>%
  plot_ly(x = ~month, y = ~violation_count, type = 'scatter', mode = 'markers') 
```

